### PR TITLE
Removing Velocity from Spring Boot - Deprecated

### LINKED ISSUE #48: velocity is not supported by spring boot anymore
There are couple of deprecated classes

https://github.com/ozkanpakdil/spring-comparing-template-engines/blob/3c9ed41bb41dcfe750082c763aa754cfcd7b1079/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java#L49
https://github.com/ozkanpakdil/spring-comparing-template-engines/blob/3c9ed41bb41dcfe750082c763aa754cfcd7b1079/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java#L50

needs to be replaced with latest approach or just remove. check https://stackoverflow.com/a/56656808/175554

### PR DESCRIPTION
**Pull request by mohitsaxenaknoldus**
Fixes #48

### CODE REVIEW

**Comment by ozkanpakdil** [comment]
can you run "mvn package" in your local and fix those problems. velocity related all beans should be cleared.

for future reference
```
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  19.600 s
[INFO] Finished at: 2021-11-27T15:39:28Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project spring-comparing-template-engines: Compilation failure: Compilation failure: 
[ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[143,12] cannot find symbol
[ERROR]   symbol:   class VelocityConfigurer
[ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
[ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[130,9] cannot find symbol
[ERROR]   symbol:   class VelocityLayoutViewResolver
[ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
[ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[130,47] cannot find symbol
[ERROR]   symbol:   class VelocityLayoutViewResolver
[ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
[ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[144,9] cannot find symbol
[ERROR]   symbol:   class VelocityConfigurer
[ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
[ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[144,53] cannot find symbol
[ERROR]   symbol:   class VelocityConfigurer
[ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
[ERROR] -> [Help 1]
[ERROR] 

```

**Comment by ozkanpakdil** [comment]
or we should configure velocity with this way https://www.baeldung.com/spring-mvc-with-velocity I think this is better solution then deleting. after all it is nice to have freemarker and velocity test in this project.

**Comment by mohitsaxenaknoldus** [comment]
> can you run "mvn package" in your local and fix those problems. velocity related all beans should be cleared.
> 
> for future reference
> 
> ```
> [INFO] BUILD FAILURE
> [INFO] ------------------------------------------------------------------------
> [INFO] Total time:  19.600 s
> [INFO] Finished at: 2021-11-27T15:39:28Z
> [INFO] ------------------------------------------------------------------------
> [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project spring-comparing-template-engines: Compilation failure: Compilation failure: 
> [ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[143,12] cannot find symbol
> [ERROR]   symbol:   class VelocityConfigurer
> [ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
> [ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[130,9] cannot find symbol
> [ERROR]   symbol:   class VelocityLayoutViewResolver
> [ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
> [ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[130,47] cannot find symbol
> [ERROR]   symbol:   class VelocityLayoutViewResolver
> [ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
> [ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[144,9] cannot find symbol
> [ERROR]   symbol:   class VelocityConfigurer
> [ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
> [ERROR] /home/mlinux/tmp/tmp/spring-comparing-template-engines/src/main/java/com/jeroenreijn/examples/configuration/WebMvcConfig.java:[144,53] cannot find symbol
> [ERROR]   symbol:   class VelocityConfigurer
> [ERROR]   location: class com.jeroenreijn.examples.configuration.WebMvcConfig
> [ERROR] -> [Help 1]
> [ERROR] 
> ```

Fixed

**Comment by mohitsaxenaknoldus** [comment]
> or we should configure velocity with this way https://www.baeldung.com/spring-mvc-with-velocity I think this is better solution then deleting. after all it is nice to have freemarker and velocity test in this project.

I am not that used to Spring yet. I saw the dependencies are good so I am guessing it's the implementation that needs change.

**Pull request closed without merging**
